trend_task:
  description: >
    Using the internet, social media, news outlets, and online forums find current the top 20 trending topics on {topic}.
    Prefer items with strong momentum and concrete signals (news volume, searches, notable events/launches)
    For each trend provide a name, brief description (1-2 sentences), relevance to the topic and why it's trending now.
  expected_output: >
    A list of trends with name, brief description, relevance to the topic and why it's trending now.
  agent: trend_researcher
  output_file: output/trends.json

strategy_task:
  description: >
    Evaluate the researched trends for Mastercard. Score 0-10 on Brand alignment, Market potential, and Customer engagement on trends related to {topic}.
    Provide strategic recommendations to leverage trends and enhance Mastercard's brand strategy to improve market positioning and customer engagement.
    Select top 3 trends. Do not repeat similar trends.
  expected_output: >
    A list of the top 3 trends with scores for Brand alignment, Market potential, and Customer engagement.
    Include strategic recommendations for each trend. There should be no repeated or similar trends.
  agent: strategist
  context:
    - trend_task
  output_file: output/strategy.json

campaign_task:
  description: >
    Design a comprehensive and elaborate marketing campaign for Mastercard based each of the top 3 trends identified.
    Include campaign objectives, target audience, key messages, channels, tactics, timeline, and metrics for success.
    For each topic write a 300 word detailed plan. Include details on Mastercard offers, benefits and loyalty programs.
  expected_output: >
    A detailed marketing campaign plan for each of the top 3 trends with elaborate sections on campaign details, objectives, target audience, key messages, channels, tactics, timeline, and metrics for success.
  agent: campaign_designer
  context:
    - strategy_task
  output_file: output/campaigns.json

pdf_generation_task:
  description: >
    Generate a PDF report from the campaigns in the json file output/campaigns.json.
  expected_output: >
    A PDF report summarizing the marketing campaigns with file name output/campaigns.pdf.
  agent: campaign_designer